apiVersion: apps/v1
kind: Deployment
metadata:
  name: patroni
  labels:
    app: test2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test2
  template:
    metadata:
      labels:
        app: test2
    spec:
      containers:
        - name: patroni
          image: k8-registry:5000/testnginx:v1
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: reg-cred-secret


